# Generated by Django 6.0.1 on 2026-01-21 06:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('gid', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('resource_type', models.CharField(default='project', max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('archived', models.BooleanField(default=False)),
                ('color', models.CharField(blank=True, max_length=20, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('html_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('due_on', models.DateField(blank=True, null=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('start_on', models.DateField(blank=True, null=True)),
                ('default_view', models.CharField(choices=[('list', 'List'), ('board', 'Board'), ('calendar', 'Calendar'), ('timeline', 'Timeline')], default='list', max_length=20)),
                ('public', models.BooleanField(default=False)),
                ('current_status_color', models.CharField(blank=True, max_length=20, null=True)),
                ('current_status_text', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'projects',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('gid', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('resource_type', models.CharField(default='team', max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('html_description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'teams',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('gid', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('resource_type', models.CharField(default='user', max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('photo_21x21', models.URLField(blank=True, null=True)),
                ('photo_27x27', models.URLField(blank=True, null=True)),
                ('photo_36x36', models.URLField(blank=True, null=True)),
                ('photo_60x60', models.URLField(blank=True, null=True)),
                ('photo_128x128', models.URLField(blank=True, null=True)),
                ('photo_1024x1024', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('gid', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('resource_type', models.CharField(default='workspace', max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('email_domains', models.JSONField(blank=True, default=list)),
                ('is_organization', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'workspaces',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('gid', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('resource_type', models.CharField(default='section', max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='api.project')),
            ],
            options={
                'db_table': 'sections',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('gid', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('resource_type', models.CharField(default='task', max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('resource_subtype', models.CharField(choices=[('default_task', 'Default Task'), ('milestone', 'Milestone'), ('approval', 'Approval')], default='default_task', max_length=20)),
                ('completed', models.BooleanField(default=False)),
                ('approval_status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('changes_requested', 'Changes Requested')], default='pending', max_length=20, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('html_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('due_on', models.DateField(blank=True, null=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('start_on', models.DateField(blank=True, null=True)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('liked', models.BooleanField(default=False)),
                ('num_likes', models.IntegerField(default=0)),
                ('num_subtasks', models.IntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subtasks', to='api.task')),
                ('projects', models.ManyToManyField(blank=True, related_name='tasks', to='api.project')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to='api.user')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_tasks', to='api.user')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to='api.user')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='api.workspace')),
            ],
            options={
                'db_table': 'tasks',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='api.team'),
        ),
        migrations.AddField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_projects', to='api.user'),
        ),
        migrations.AddField(
            model_name='team',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='api.workspace'),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('gid', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('resource_type', models.CharField(default='tag', max_length=5)),
                ('name', models.CharField(max_length=255)),
                ('color', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='api.workspace')),
            ],
            options={
                'db_table': 'tags',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='api.workspace'),
        ),
        migrations.CreateModel(
            name='TaskTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tag')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.task')),
            ],
            options={
                'db_table': 'task_tags',
                'unique_together': {('task', 'tag')},
            },
        ),
        migrations.CreateModel(
            name='ProjectMembership',
            fields=[
                ('gid', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('resource_type', models.CharField(default='project_membership', max_length=20)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
            options={
                'db_table': 'project_memberships',
                'unique_together': {('user', 'project')},
            },
        ),
        migrations.CreateModel(
            name='WorkspaceMembership',
            fields=[
                ('gid', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('resource_type', models.CharField(default='workspace_membership', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.workspace')),
            ],
            options={
                'db_table': 'workspace_memberships',
                'unique_together': {('user', 'workspace')},
            },
        ),
    ]
