# Generated by Django 6.0.1 on 2026-01-21 07:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='photo_1024x1024',
        ),
        migrations.RemoveField(
            model_name='user',
            name='photo_128x128',
        ),
        migrations.RemoveField(
            model_name='user',
            name='photo_21x21',
        ),
        migrations.RemoveField(
            model_name='user',
            name='photo_27x27',
        ),
        migrations.RemoveField(
            model_name='user',
            name='photo_36x36',
        ),
        migrations.RemoveField(
            model_name='user',
            name='photo_60x60',
        ),
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='workspaces',
            field=models.ManyToManyField(related_name='users', through='api.WorkspaceMembership', to='api.workspace'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('gid', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('resource_type', models.CharField(default='attachment', max_length=15)),
                ('name', models.CharField(max_length=255)),
                ('resource_subtype', models.CharField(default='external', max_length=20)),
                ('size', models.PositiveIntegerField(blank=True, null=True)),
                ('download_url', models.URLField(blank=True, null=True)),
                ('view_url', models.URLField(blank=True, null=True)),
                ('permanent_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_attachments', to='api.user')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='api.task')),
            ],
            options={
                'db_table': 'attachments',
            },
        ),
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('gid', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('resource_type', models.CharField(default='custom_field', max_length=15)),
                ('name', models.CharField(max_length=255)),
                ('resource_subtype', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('enum', 'Enum'), ('multi_enum', 'Multi-Enum'), ('date', 'Date'), ('people', 'People')], default='text', max_length=15)),
                ('type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('enum', 'Enum'), ('multi_enum', 'Multi-Enum'), ('date', 'Date'), ('people', 'People')], default='text', max_length=15)),
                ('description', models.TextField(blank=True, null=True)),
                ('enum_options', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_custom_fields', to='api.user')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='api.workspace')),
            ],
            options={
                'db_table': 'custom_fields',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('gid', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('resource_type', models.CharField(default='event', max_length=10)),
                ('action', models.CharField(choices=[('task_created', 'Task Created'), ('task_updated', 'Task Updated'), ('task_deleted', 'Task Deleted'), ('project_created', 'Project Created'), ('project_updated', 'Project Updated'), ('project_deleted', 'Project Deleted'), ('comment_added', 'Comment Added')], max_length=50)),
                ('resource', models.JSONField()),
                ('change', models.JSONField(blank=True, null=True)),
                ('parent', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='api.user')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='api.workspace')),
            ],
            options={
                'db_table': 'events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectStatus',
            fields=[
                ('gid', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('resource_type', models.CharField(default='project_status', max_length=15)),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField(blank=True, null=True)),
                ('html_text', models.TextField(blank=True, null=True)),
                ('color', models.CharField(choices=[('green', 'Green'), ('yellow', 'Yellow'), ('red', 'Red'), ('blue', 'Blue')], default='green', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_project_statuses', to='api.user')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='api.project')),
            ],
            options={
                'db_table': 'project_statuses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('gid', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('resource_type', models.CharField(default='story', max_length=10)),
                ('resource_subtype', models.CharField(choices=[('comment', 'Comment'), ('system', 'System')], default='comment', max_length=20)),
                ('text', models.TextField(blank=True, null=True)),
                ('html_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_stories', to='api.user')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='api.task')),
            ],
            options={
                'db_table': 'stories',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('gid', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('resource_type', models.CharField(default='webhook', max_length=10)),
                ('callback_url', models.URLField()),
                ('method', models.CharField(default='POST', max_length=10)),
                ('filters', models.JSONField(default=list)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_webhooks', to='api.user')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='api.workspace')),
            ],
            options={
                'db_table': 'webhooks',
            },
        ),
        migrations.CreateModel(
            name='CustomFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_value', models.TextField(blank=True, null=True)),
                ('number_value', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('date_value', models.DateField(blank=True, null=True)),
                ('enum_value', models.CharField(blank=True, max_length=255, null=True)),
                ('custom_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.customfield')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.project')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.task')),
            ],
            options={
                'db_table': 'custom_field_values',
                'unique_together': {('custom_field', 'project'), ('custom_field', 'task')},
            },
        ),
    ]
