# Generated by Django 6.0.1 on 2026-01-21 08:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_user_photo_1024x1024_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('gid', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('resource_type', models.CharField(default='allocation', max_length=15)),
                ('resource', models.JSONField()),
                ('work_object', models.JSONField()),
                ('effort_value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('effort_unit', models.CharField(choices=[('percentage', 'Percentage'), ('hours', 'Hours')], default='percentage', max_length=20)),
                ('start_on', models.DateField()),
                ('end_on', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='api.workspace')),
            ],
            options={
                'db_table': 'allocations',
                'ordering': ['-created_at'],
            },
        ),
    ]
